# Generated by Django 3.2.12 on 2022-03-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-add_time']},
        ),
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-created_at']},
        ),
    ]
